export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const SET_GENERAL_INFORMATION = "SET_GENERAL_INFORMATION";
export const SET_CONDITIONS = "SET_CONDITIONS";
export const SET_MEDICAL_QUESTIONS = "SET_MEDICAL_QUESTIONS";
export const SET_AGREE_TO_TERMS = "SET_AGREE_TO_TERMS";
export const SET_IS_CURRENT_STEP_VALID = "SET_IS_CURRENT_STEP_VALID";
